name: Check Links
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Install awesome_bot
        run: gem install awesome_bot
      - name: Check non-Medium URLs
        run: |
          awesome_bot README.md --allow-redirect --request-delay 0.2 --white-list medium.com
      - name: Check Medium URLs
        run: |
          medium_urls=$(grep -Eo 'https?://[^[:space:]]+medium.com[^[:space:]]*' README.md)
          if [ ! -z "$medium_urls" ]; then
            echo "$medium_urls" | awesome_bot --allow-redirect --request-delay 5 -
          else
            echo "No Medium URLs found"
          fi
